# Generated by Django 3.2.4 on 2021-12-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0002_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='uploads/%Y/'),
        ),
    ]
