# Generated by Django 3.2.4 on 2022-01-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='biblioteca.categoria_livro')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('numero_pagina', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('isbn', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('data_entrada', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
