# Generated by Django 3.2.4 on 2022-01-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('numero_docente', models.CharField(max_length=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='docente.categoria')),
                ('grau_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='docente.docente_grau_academico')),
            ],
        ),
    ]
