# Generated by Django 3.2.4 on 2022-02-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_orientador'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientador',
            name='numero_orientados',
            field=models.IntegerField(default=1),
        ),
    ]
