# Generated by Django 3.2.4 on 2022-09-25 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0007_orientador_numero_orientados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade_Curricular_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='docente.docente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='curso.curso')),
                ('unidadeCurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='unidade_curricular.unidadecurricular')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.periodo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='docente.estado_docente')),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.ano')),
                ('ano_letivo', models.FileField(default=2022, upload_to='')),
                ('tremestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.tremestre')),
                ('data_registro', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
