# Generated by Django 3.2.4 on 2022-09-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0008_unidade_curricular_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade_curricular_docente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='docente.estado_docente'),
        ),
    ]
