# Generated by Django 3.2.4 on 2022-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0009_alter_unidade_curricular_docente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade_curricular_docente',
            name='ano_letivo',
            field=models.CharField(default=2022, max_length=190),
        ),
    ]
