# Generated by Django 3.2.4 on 2022-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao_Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
    ]
