# Generated by Django 3.2.4 on 2022-01-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_opcao_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador_Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
