# Generated by Django 3.2.4 on 2022-02-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_contador_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tremestre',
            name='ano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.ano'),
            preserve_default=False,
        ),
    ]
