# Generated by Django 3.2.4 on 2022-01-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoa.pessoa')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='curso.curso')),
                ('grau_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.grau_academico')),
                ('numero_estudante', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('area_formacao', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('curso_frequentado', models.CharField(max_length=190)),
                ('media_conclusao', models.CharField(blank=True, max_length=2, null=True)),
                ('instituicao_origem', models.CharField(max_length=120)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
