# Generated by Django 3.2.4 on 2022-01-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='curso.curso')),
                ('opcao_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.opcao_matricula')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.ano')),
                ('tremestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.tremestre')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.periodo')),
                ('data', models.DateField(max_length=20)),
                ('nota_exame', models.CharField(blank=True, default=' ', max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_estudante',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='media_conclusao',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
