# Generated by Django 3.2.4 on 2022-01-12 23:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='curso.curso')),
                ('opcao_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.opcao_matricula')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.ano')),
                ('tremestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.tremestre')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.periodo')),
                ('dataMatricula', models.DateField(default=django.utils.timezone.now)),
                ('nota_exame', models.CharField(blank=True, default=' ', max_length=2, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
