# Generated by Django 3.2.4 on 2022-01-20 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_motivo_reclamacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='curso.curso')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.motivo_reclamacao')),
                ('data_reclamacao', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.CharField(default='Em Analise', max_length=20, null=True)),
                ('descricao', models.CharField(default='', max_length=3000, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
