# Generated by Django 3.2.4 on 2022-01-27 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='data_reclamacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
