# Generated by Django 3.2.4 on 2022-02-09 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_curricular', '0004_unidadecurricular_curso_carga_horaria'),
        ('aluno', '0005_alter_reclamacao_data_reclamacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmar_Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='curso.curso')),
                ('ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.ano')),
                ('tremestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.tremestre')),
                ('data_confirmacao', models.DateField(default=django.utils.timezone.now)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='config.periodo')),
                ('responsavel', models.CharField(blank=True, max_length=190, null=True)),
                ('numero_recibo', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cadeiras_atraso', models.ManyToManyField(blank=True, null=True, to='unidade_curricular.UnidadeCurricular_Curso')),
            ],
        ),
    ]
