# Generated by Django 3.2.4 on 2022-02-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_confirmar_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmar_matricula',
            options={'ordering': ['-aluno']},
        ),
    ]
