# Generated by Django 3.2.4 on 2022-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_alter_confirmar_matricula_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
