# Generated by Django 3.2.4 on 2022-02-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_alter_aluno_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmar_matricula',
            name='cadeiras_atraso',
        ),
    ]
