# Generated by Django 3.2.4 on 2022-09-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_remove_confirmar_matricula_cadeiras_atraso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadeirasAtraso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='aluno.confirmar_matricula')),
                ('ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.ano')),
                ('tremestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.tremestre')),
                ('responsavel', models.CharField(blank=True, max_length=190, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-aluno'],
            },
        ),
    ]
