# Generated by Django 3.2.4 on 2021-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=190)),
                ('sigla', models.CharField(blank=True, default=' ', max_length=60, null=True)),
            ],
        ),
    ]
