# Generated by Django 3.2.4 on 2021-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_curricular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
