# Generated by Django 3.2.4 on 2022-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_curricular', '0003_unidadecurricular_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular_curso',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
